### ISSUE TITLE
AzureAD missleading Warning

### ISSUE THREAD

**Issue by PetreHoffmann** [bwya77/PowerShell#2]
https://github.com/bwya77/PowerShell/blob/e4b5632cfdaff639afd673162bf0dc1839f5c896/Office%20365/Connect-Office365.ps1#L228

You wrote:    `Write-Warning "SkypeOnlineConnector Module is not present!"`
Need to be:   `Write-Warning "AzureAD Module is not present!"`

**Comment by PetreHoffmann** [comment]
Thanks

**Comment by PetreHoffmann** [comment]
Line Update

https://github.com/bwya77/PowerShell/blob/3d6ab79c435d7ed768724dd5fe843182e53350c9/Office%20365/Connect-Office365.ps1#L113

**Comment by bwya77** [comment]
merged pull request, thanks for your work :)
